### ISSUE TITLE
./node_modules/@solana/buffer-layout-utils/lib/esm/web3.mjs Can't import the named export 'PublicKey' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by zihangg** [solana-labs/buffer-layout-utils#6]
Recently did a fresh install of my application, seems like this issue just popped up.

**Comment by masnasri-a** [comment]
same

**Comment by carrey-dan** [comment]
same.After re-importing the solana package, the package is forced to be imported every time, and it is useless to delete it, which makes web3js unusable. Hope this can be resolved soon.

**Comment by RetroDudeDev** [comment]
Was going to come here to report the same thing, anyone found a solution?

**Comment by jstarry** [comment]
Thanks for raising this issue, I ran into this as well. Hoping this fix will resolve it: https://github.com/solana-labs/solana/pull/25399

**Comment by jstarry** [comment]
`@solana/web3.js` version 1.43.1 should fix this issue!
